package:
  name: tempered_pf
  version: 0.0.1

source:
  path: ..

requirements:
  build:
    - fortress
    - json-fortran
    - fypp
    - fruitpy
    - fruit


  run:
    - fortress
    - fruitpy
    - json-fortran


build:
  detect_binary_files_with_prefix: True
  

# test:
#   requires:
#     - tempered_pf
#   commands:
#     - tpf_driver --help

#  imports:
    #- FRUIT
    