package:
  name: tempered_pf
  version: 0.0.1

source:
  path: ..

build:
  detect_binay_files_with_prefix: true

  binary_has_prefix_files:
    - ../tpf_driver
    
requirements:
  build:
    - fortress
    - json-fortran
    - fypp
    - fruitpy
    - fruit


  run:
    - fortress
    - fruitpy
    - json-fortran
    - openblas
    - mpich2
    
build:
  detect_binary_files_with_prefix: True

  binary_has_prefix_files:
    - ../tpf_driver
    - ../bin/tpf_driver
    - tpf_driver
test:
  requires:
    - tempered_pf
  commands:
    - pwd
    - tpf_driver --nsim 1

#  imports:
    #- FRUIT
    
