package:
  name: tempered_pf
  version: 0.0.1

source:
  path: ..

requirements:
  build:
    - fortress
    - json-fortran
    - gcc
    - fypp
  run:
    - fortress
    - json-fortran
    - libgcc
    - libgfortran