package:
  name: tempered_pf
  version: 0.0.1

source:
  path: ..

build:
  script_env:
    - CONDA_PREFIX

  detect_binay_files_with_prefix: true

  binary_has_prefix_files:
    - ../tpf_driver
    
requirements:
  build:
    - fortress
    - json-fortran
    - fypp
    - fruitpy
    - fruit


  run:
    - fortress
    - fruitpy
    - json-fortran


build:
  detect_binary_files_with_prefix: True
  

# test:
#   requires:
#     - tempered_pf
#   commands:
#     - tpf_driver --help

#  imports:
    #- FRUIT
    
